.\" Manpage for conview
.\" Author of this manpage is Aitzaz Imtiaz <aitzazimtiaz.ai@gmail.com>, contact him to correct errors or typos.
.\" This man page is released into the public domain by B-Consortium under B-License and Freedom to Public Access
.TH conview 6 "3 August 2023" "1.0" "bmake User Manual"
.SH NAME
bmake \- bmake
.SH DESCRIPTION
This command was made by B-Consortium as a C-Styled automatic directory generator, working as a main primary aid
so that project automation and build becomes easy
.PP
Acting as a automatic content generator
.SH AUTHOR
Aitzaz Imtiaz ( https://github.com/AitzazImtiaz )
.SH COPYRIGHT
bmaker was made by B-Consortium under the philosophy that public access and development be encouraged due to which
the consortium passed its own B-License which allows anyone to copy this work without necessary attributions.
